INCLUDEPATH=-I/usr/src/linux-headers-3.10-2-common/include/ \
	    -I/usr/src/linux-headers-3.10-2-common/arch/x86/include/ \
	    
CFLAGS+= -nostdinc -D_POSIX_C_SOURCE ${INCLUDEPATH} -Wall -Wextra

all: base
